---
- name: Automate minimal + hardened ubuntu/rocky server
  hosts: all
  become: true
  become_method: ansible.builtin.sudo

  vars_files:
    - roles/linux_baseline/vars/main.yml

  roles:
    - role: linux_baseline
