---
- name: Install fail2ban
  ansible.builtin.package:
    name: fail2ban
    state: present
  tags: security

- name: Configure fail2ban
  ansible.builtin.blockinfile:
    path: /etc/fail2ban/jail.d/sshd.conf
    create: true
    mode: "0644"
    block: |
      [sshd]
      enabled  = true
      port     = {{ linux_baseline_ssh_port }}
      filter   = sshd
      logpath  = {{ linux_baseline_auth_log }}
      maxretry = 5
      bantime  = 24h
      findtime = 10m
  notify: Restart fail2ban service
  tags: security

- name: Start fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: true
  tags: security
