- name: Ensuring libpam-tmpdir is installed for PAM session isolation [AUTH-9262]
  ansible.builtin.apt:
    name: libpam-tmpdir
    state: present
    update_cache: true
  tags: lynis

- name: Ensuring apt-listchanges is installed for change tracking [PKGS-7388]
  ansible.builtin.apt:
    name: apt-listchanges
    state: present
  tags: lynis

- name: Ensuring auditd is installed
  ansible.builtin.apt:
    name: auditd
    state: present
  tags: lynis

- name: Configure apt-listchanges for non-interactive automation
  ansible.builtin.debconf:
    name: apt-listchanges
    question: apt-listchanges/confirm
    value: "false"
    vtype: select
  tags: lynis

- name: Ensuring Fail2ban is installed
  ansible.builtin.package:
    name: fail2ban
    state: present
  tags: lynis

- name: Copy Fail2ban jail.conf to jail.local to protect configuration override [TOOL-5102]
  ansible.builtin.copy:
    src: /etc/fail2ban/jail.conf
    dest: /etc/fail2ban/jail.local
    remote_src: true
    force: false
    mode: '0644'
  tags: lynis

- name: Check which compilers exist
  ansible.builtin.stat:
    path: "{{ item }}"
  loop:
    - /usr/bin/gcc
    - /usr/bin/g++
    - /usr/bin/make
    - /usr/bin/cc
  register: linux_baseline_compiler_stats
  tag: lynis

- name: Restrict compilers to root user only [BANN-9130]
  ansible.builtin.file:
    path: "{{ item.item }}"
    mode: '0700'
    owner: root
    group: root
  loop: "{{ linux_baseline_compiler_stats.results }}"
  when: item.stat.exists
  tags: lynis

- name: Restrict system crontab permission [FILE-7524]
  ansible.builtin.file:
    path: /etc/crontab
    mode: '0600'
    owner: root
    group: root
  tags: lynis
