---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"
  tags: always

- name: Run base configuration
  ansible.builtin.include_tasks: base.yml
  tags: always

- name: Apply security baseline (depending on distro)
  ansible.builtin.include_tasks: security.yml
  tags: security

- name: Install and configure fail2ban
  ansible.builtin.include_tasks: fail2ban.yml
  tags: security

- name: Download & Install tailscale
  ansible.builtin.include_tasks: tailscale.yml
  tags: tailscale

- name: Apply SSH hardening
  ansible.builtin.include_tasks: ssh.yml
  tags: ssh

- name: Run system tweaks
  ansible.builtin.include_tasks: system.yml
  tags: system

- name: Apply Lynis patches
  ansible.builtin.include_tasks: lynis.yml
  tags: lynis
