- name: Configure Firewall (Debian)
  ansible.builtin.include_tasks: security_ufw.yml
  when: ansible_os_family == "Debian"

- name: Configure Firewall (RedHat)
  ansible.builtin.include_tasks: security_firewalld.yml
  when: ansible_os_family == "RedHat"
