---
- name: Setting UFW
  community.general.ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - { direction: "incoming", policy: "deny" }
    - { direction: "outgoing", policy: "allow" }
  tags: security
  # noqa: args[module]

- name: Allow OpenWeb Traffic Ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "80"
    - "443"
  tags: security

- name: Allow tailscale interface
  community.general.ufw:
    rule: allow
    interface: tailscale0
    direction: in
  tags: security

- name: Rate-limit SSH custom port
  community.general.ufw:
    rule: limit
    port: "{{ linux_baseline_ssh_port }}"
    proto: tcp
  tags: security

- name: Enable ufw
  community.general.ufw:
    state: enabled
  tags: security

- name: Configure automatic updates (Debian)
  when: ansible_facts['os_family'] == "Debian"
  block:
    - name: Enable automatic security updates
      ansible.builtin.debconf:
        name: unattended-upgrades
        question: unattended-upgrades/enable_auto_updates
        value: "true"
        vtype: boolean
