---
- name: Install firewalld
  ansible.builtin.package:
    name: firewalld
    state: present
  tags: security

- name: Start and enable firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true
  tags: security

- name: Allow HTTP/HTTPS
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - http
    - https
  when: linux_baseline_allow_web_ports | default(false) | bool
  tags: security

- name: Allow Tailscale
  ansible.posix.firewalld:
    zone: trusted
    interface: tailscale0
    permanent: true
    state: enabled
  tags: security

- name: Rate limit SSH
  ansible.posix.firewalld:
    rich_rule: 'rule family="ipv4" source address="0.0.0.0/0" port port="{{ linux_baseline_ssh_port }}" protocol="tcp" limit value="5/m" accept'
    permanent: true
    state: enabled
  tags: security

- name: Enable dnf-automatic timer
  ansible.builtin.systemd:
    name: dnf-automatic-install.timer
    state: started
    enabled: true
  when: ansible_facts['os_family'] == "RedHat"
  tags: security

- name: Ensure policycoreutils-python-utils is installed (Required for SELinux management)
  ansible.builtin.dnf:
    name: policycoreutils-python-utils
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Allow SSH to use port 2222 in SELinux
  community.general.seport:
    ports: 2222
    proto: tcp
    setype: ssh_port_t
    state: present
  when: ansible_facts['os_family'] == "RedHat"
