---
- name: Install zram
  ansible.builtin.apt:
    name: zram-tools
    state: present
  tags: system

- name: Ensuring zram is up and running
  ansible.builtin.systemd:
    name: zramswap
    state: started
    enabled: true
  when: lookup('env', 'GITHUB_ACTIONS') != 'true'
  tags: system

- name: Disable and remove swap.img
  ansible.builtin.command: swapoff /swap.img
  failed_when: false
  changed_when: false
  tags: system

- name: Remove swap.img from fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: ".*swap.img*"
    state: absent
  tags: system

- name: Delete swapfile
  ansible.builtin.file:
    path: /swap.img
    state: absent
  tags: system
