linux_baseline_packages:
  - curl
  - git
  - btop
  - vim
  - openssh-server
  - fail2ban
  - unattended-upgrades
  - apt-listchanges
  - "{{ linux_baseline_firewall_package }}"

linux_baseline_zram_package: zram-tools
linux_baseline_zram_service: zramswap
linux_baseline_firewall_package: ufw
linux_baseline_admin_group: sudo
linux_baseline_auth_log: /var/log/auth.log
linux_baseline_audit_package: auditd
