---
# Set to true if this server will act as a public-facing web server
linux_baseline_allow_web_ports: false

# Your username
linux_baseline_username: "tanvir"

# Path to ssh public key
linux_baseline_pub_key: "~/.ssh/hp.pub"

# Port for ssh
linux_baseline_ssh_port: "2222"
