linux_baseline_packages:
  - curl
  - git
  - btop
  - vim
  - openssh-server
  - fail2ban
  - dnf-automatic

linux_baseline_zram_package: zram-generator
linux_baseline_zram_service: zram-swap@zram0.service
linux_baseline_firewall_package: firewalld
linux_baseline_admin_group: wheel
linux_baseline_auth_log: /var/log/secure
