name: Test Ansible Playbook Execution

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          pip install ansible ansible-lint
          ansible-galaxy collection install ansible.posix community.general

      - name: Lint playbook
        run: ansible-lint playbook.yml

  dry-run:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ansible & requirements
        run: |
          pip install ansible
          ansible-galaxy collection install ansible.posix community.general

      - name: Create a mock env
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -t ed25519 -N ""

          sudo useradd -m testuser

          sudo dd if=/dev/zero of=/swap.img bs=1M count=10
          sudo mkswap /swap.img
          sudo swapon /swap.img || true

      - name: Create test vars file
        run: |
          cat > vars/config.yml << EOF
          username: "testuser"
          pub_key: "~/.ssh/id_ed25519.pub"
          ssh_port: "2222"

          mount_ntfs: false
          ntfs_drive_uuid: "dummy-uuid"
          ntfs_mount_path: "/mnt/Files"
          EOF

      - name: Run playbook in check mode
        run: |
          ansible-playbook playbook.yml \
            -i "localhost," \
            -c local \
            --check \
            -e "GITHUB_ACTIONS=true"
