---
- name: Restart ssh service
  ansible.builtin.systemd:
    name: "{% if ansible_facts['os_family'] == 'Debian' %}ssh{% else %}sshd{% endif %}"
    state: restarted
  failed_when: false

- name: Restart fail2ban service
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
  failed_when: false

- name: Reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  failed_when: false
